### ISSUE TITLE
multiple projects should not be in the same repo, but in different branches

### ISSUE THREAD

**Issue by skye5000** [Nekoyre/Kythi#3]
I recommend creating a github organization with the name "Kythi" and transferring those branches to separate repos in the github organization (called "backend", "frontend", etc)

**Comment by NahSahh** [comment]
no neko wants it on his account

**Comment by NahSahh** [comment]
separate repos gay

**Comment by Nekoyre** [comment]
1. we did that at some point
2. pros of having this on my account is that vercel will host frontend without me paying anything
3. also free repositories (im a repo farmer)

(and i dont want 4 repos for the same thing)

**Comment by skye5000** [comment]
oki, sorry for bothering
